# @Author: fabio
# @Date:   2016-03-09T18:44:10+01:00
# @Last modified by:   fabio
# @Last modified time: 2016-03-10T18:16:43+01:00



baseurl = "http://blog.fabio.xyz/"
languageCode = "es-es"
title = "avances123"
theme = "angels-ladder"
#disqusShortname = "avances123"
canonifyurls = true






[Params]
subtitle = "Ahora es cuando"
twitter = "https://twitter.com/avances123"
github = "https://github.com/avances123"
showsRSS = true
profile = "/images/profile.png"
copyright = "Written by Fabio Rueda"
analytics = "UA-XXXXXXXX-X"
#shareThis = "181865b5-e6c7-4a9b-b78e-d068ee58a2c8"
