baseurl = "http://blog.fabio.xyz/"
languageCode = "es-es"
title = "avances123"
theme = "angels-ladder"
paginate = 8
canonifyurls = true


[taxonomies]
tag = "tags"
category = "categories"
language = "languages"



[Params]
subtitle = "Instalo algo y opino al respecto"
twitter = "https://twitter.com/avances123"
github = "https://github.com/avances123"
showsRSS = true
profile = "/images/profile.png"
copyright = "Written by Fabio Rueda"
analytics = "UA-18805523-1"
#shareThis = "181865b5-e6c7-4a9b-b78e-d068ee58a2c8"
